# Generated by Django 2.1.2 on 2018-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_academic_score_facultycourse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeweightage',
            name='assign1_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='assign2_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='assign3_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='end_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='mid1_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='mid2_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='presentation_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='project_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='quiz1_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='quiz2_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='quiz3_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='tut1_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='tut2_marks',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
