# Generated by Django 2.1.2 on 2018-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20181101_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeweightage',
            old_name='assign1',
            new_name='tmarks',
        ),
        migrations.RenameField(
            model_name='gradeweightage',
            old_name='assign1_marks',
            new_name='wmarks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='assign2',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='assign2_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='assign3',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='assign3_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='end',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='end_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='mid1',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='mid1_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='mid2',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='mid2_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='presentation_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='project_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz1',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz1_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz2',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz2_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz3',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='quiz3_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='tut1',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='tut1_marks',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='tut2',
        ),
        migrations.RemoveField(
            model_name='gradeweightage',
            name='tut2_marks',
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='Exam_Type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
