# Generated by Django 2.1.2 on 2018-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181101_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='M1_07',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='M2_07',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='M3_07',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='M4_07',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='M5_07',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
