# Generated by Django 2.1.2 on 2018-11-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181102_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Registration_Id',
            new_name='Id',
        ),
        migrations.RemoveField(
            model_name='academic_score',
            name='Registration_Id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Registration_Id',
        ),
    ]
