# Generated by Django 2.1.2 on 2018-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20181102_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Academic_Course_Id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Student_Id',
        ),
        migrations.AddField(
            model_name='academic_score',
            name='Semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeschema',
            name='Semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gradeweightage',
            name='Semester',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
