# Generated by Django 2.1.2 on 2018-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20181103_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.BinaryField(null=True),
        ),
    ]
