# Generated by Django 2.1.2 on 2018-11-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_score',
            name='course',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
