# Generated by Django 2.1.2 on 2018-11-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20181111_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_score',
            name='Academic_Course_Id',
        ),
        migrations.RemoveField(
            model_name='academic_score',
            name='Facultycourse_Id',
        ),
        migrations.RemoveField(
            model_name='academic_score',
            name='Student_Id',
        ),
        migrations.DeleteModel(
            name='Academic_score',
        ),
    ]
