# Generated by Django 2.1.2 on 2018-11-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20181111_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Type', models.CharField(max_length=20)),
                ('Marks', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Marks_perc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Semester', models.CharField(max_length=10, null=True)),
                ('Academic_Course_Id', models.ForeignKey(default='C1', on_delete=django.db.models.deletion.CASCADE, to='student.Academic_Course')),
                ('Facultycourse_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Faculty')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
