# Generated by Django 2.1.2 on 2018-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_gradeweightage_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeweightage',
            name='course',
        ),
        migrations.AddField(
            model_name='academic_score',
            name='course',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
