# Generated by Django 2.1.2 on 2018-11-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20181111_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_score',
            name='course',
        ),
    ]
