# Generated by Django 2.1.2 on 2018-11-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_gradeschema_gradeweightage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=10, null=True)),
                ('Academic_Course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Academic_Course')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
