# Generated by Django 2.1.2 on 2018-11-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Academic_Course_Id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Student_Id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
