# Generated by Django 2.2 on 2018-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='session1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
